### ISSUE TITLE
Decouple BOX account from Jay's NETID

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/digitizedbooks#3]

**Comment by alexBLR** [comment]
I'm not sure how to go about this, but we need to talk to someone who manages our Box.com account. We need to make an "app user"...if we can. https://docs.box.com/docs/app-auth#section-3-grant-access-in-enterprise-admin-console

**Comment by alexBLR** [comment]
I created this SN ticket to get an account created. INC02653646

**Comment by jkylefenton** [comment]
I have no way to test this story ... except to process a job and verify that a KDip uploads.  I won't be able to see what Box account is being used.   Think that is okay?

**Comment by alexBLR** [comment]
@jkylefenton, yes. That would be good enough.

**Comment by jkylefenton** [comment]
I tried setting the status of job "kyletest3" to "Ready for Hathi" in testdigitizedbooks, and got the following error:

ResponseError at /admin/publish/job/5/
Command # 1 (SADD rq:queues rq:queue:high) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request Method:	POST
Request URL:	https://testdigitizedbooks.library.emory.edu/admin/publish/job/5/
Django Version:	1.8
Exception Type:	ResponseError
Exception Value:	
Command # 1 (SADD rq:queues rq:queue:high) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Exception Location:	/home/httpd/digitizedbooks/env/lib/python2.7/site-packages/redis/client.py in _execute_transaction, line 2523
Python Executable:	/opt/rh/python27/root/usr/bin/python
Python Version:	2.7.8
Python Path:	
['/home/httpd/digitizedbooks',
 '/home/httpd/digitizedbooks/env/lib/python2.7/site-packages',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/anadama_workflows-0.0.1-py2.7.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/anadama-0.0.1-py2.7.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/tornado-4.1-py2.7-linux-x86_64.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/websocket-0.2.1-py2.7.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/psutil-2.2.1-py2.7-linux-x86_64.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/bottle-0.12.8-py2.7.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/python_dateutil-2.4.0-py2.7.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/pysam-0.7.8-py2.7-linux-x86_64.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/biopython-1.65-py2.7-linux-x86_64.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/networkx-1.9-py2.7.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/doit-0.25.0-py2.7.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/backports.ssl_match_hostname-3.4.0.2-py2.7.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/certifi-14.05.14-py2.7.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/greenlet-0.4.5-py2.7-linux-x86_64.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/gevent-1.0.1-py2.7-linux-x86_64.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/Cython-0.22-py2.7-linux-x86_64.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/decorator-3.4.0-py2.7.egg',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/pyinotify-0.9.5-py2.7.egg',
 '/home/src/django-eultheme',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/src/eulfedora',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools-24.0.2-py2.7.egg',
 '/opt/rh/python27/root/usr/lib64/python27.zip',
 '/opt/rh/python27/root/usr/lib64/python2.7',
 '/opt/rh/python27/root/usr/lib64/python2.7/plat-linux2',
 '/opt/rh/python27/root/usr/lib64/python2.7/lib-tk',
 '/opt/rh/python27/root/usr/lib64/python2.7/lib-old',
 '/opt/rh/python27/root/usr/lib64/python2.7/lib-dynload',
 '/opt/rh/python27/root/usr/lib64/python2.7/site-packages',
 '/opt/rh/python27/root/usr/lib/python2.7/site-packages',
 '/home/digitizedbooks']
Server time:	Wed, 11 Oct 2017 08:21:39 -0400

**Comment by jkylefenton** [comment]
I was unable to complete testing the other day, the test server returned a 500 error.   I added a note to the story in waffle.


Kyle Fenton
Lead, Digitization &
  Digital Curation
Emory University Libraries
ph. 404-727-5726
________________________________

**Comment by alexBLR** [comment]
Thank you, Kyle. I will take a look.
