### ISSUE TITLE
FTPS function from DigitizedBooks to Zephir system not working

### ISSUE THREAD

**Issue by jkylefenton** [emory-libraries/digitizedbooks#7]
https://digitizedbooks.library.emory.edu/ is currently having an issue with uploading any MARC records to Berkeley's Zephir system, which prevents jobs from proceeding to the next step (packaging and uploading to HathiTrust).   
 
Not super urgent, but no newly digitized books will be available on HathiTrust until the issue is resolved.

**Comment by jkylefenton** [comment]
In addition, it looks like the app has generated no new Kdips since at least January 11 -- including the following:
010001131395
010001131403
010001131402
010001334059
010001131397
010001131398
010001131399	
010001131396
010000351768
010001131400
010001131392
010001131394
010001261699
010001131391
010001338920
010001131393

**Comment by alexBLR** [comment]
Extra space in job names was causing this issue.
